
version: 2

sources:
  - name: example
    description: 'First DBT'
    project: new-demo-318508
    dataset: Demo
    #freshness:
      #warn_after: {count: 20, period: hour}
      #error_after: {count: 30, period: hour}
    #loaded_at_field:
    tables:
      - name: students
        columns:
          - name: id
            description: "The primary key for this table"
            tests:

              - not_null
              - unique
              
    tables:
     - name: students1
       columns:
         - name: id
           description: "The primary key for this table"
           tests:
             - not_null
             - unique
